---
# handlers file for disable_ipv6
- name: reboot
  reboot:
    msg: "Rebooting the system to apply IPv6 disablement."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
